language: php

php:
  - 5.5.18
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

before_script:
  - composer install

script: vendor/phpunit/phpunit/phpunit --configuration phpunit.xml.dist --coverage-text
